version: "3"

services:
  bot:
    build: .
    restart: unless-stopped
    command: python bot.py
    environment:
      BOT_TOKEN: $BOT_TOKEN
      USER_ID: $USER_ID
      SHOP_ID: $SHOP_ID
      URL: $URL